github.com:
    user: adirar111
    oauth_token: 5dfd695a05d0aaeaf808c89b6b5bee76ea877a58
    git_protocol: https
learning.github.ubc.ca:
    user: adirar01
    oauth_token: f683c6dad4fb8f44385de19aff5f538956c46314
    git_protocol: https
